# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - gcc --version && g++ --version
  - sudo apt-get install -qq bc samtools
#install: make get-deps
script: make && make test
